owner: xnaas
repo: nitter-instances

sites:
  - name: nitter.net
    url: https://nitter.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.42l.fr
    url: https://nitter.42l.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.pussthecat.org
    url: https://nitter.pussthecat.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.nixnet.services
    url: https://nitter:nitter@nitter.nixnet.services
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.fdn.fr
    url: https://nitter.fdn.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.1d4.us
    url: https://nitter.1d4.us
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.kavin.rocks
    url: https://nitter.kavin.rocks
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/in.png
  - name: nitter.unixfox.eu
    url: https://nitter.unixfox.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: nitter.domain.glass
    url: https://nitter.domain.glass
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.namazso.eu
    url: https://nitter.namazso.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: birdsite.xanny.family
    url: https://birdsite.xanny.family
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/gb.png
  - name: nitter.hu
    url: https://nitter.hu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/hu.png
  - name: nitter.moomoo.me
    url: https://nitter.moomoo.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nittereu.moomoo.me
    url: https://nittereu.moomoo.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/se.png
  - name: bird.trom.tf
    url: https://bird.trom.tf
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.it
    url: https://nitter.it
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fi.png
  - name: twitter.censors.us
    url: https://twitter.censors.us
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fr.png
  - name: nitter.grimneko.de
    url: https://nitter.grimneko.de
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: n.hyperborea.cloud
    url: https://n.hyperborea.cloud
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: nitter.ca
    url: https://nitter.ca
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: twitter.076.ne.jp
    url: https://twitter.076.ne.jp
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/jp.png
  - name: nitter.mstdn.social
    url: https://nitter.mstdn.social
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.fly.dev
    url: https://nitter.fly.dev
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/zz.png
  - name: notabird.site
    url: https://notabird.site
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/zz.png
  - name: nitter.weiler.rocks
    url: https://nitter.weiler.rocks
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.silkky.cloud
    url: https://nitter.silkky.cloud
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/fi.png
  - name: nitter.sethforprivacy.com
    url: https://nitter.sethforprivacy.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nttr.stream
    url: https://nttr.stream
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.cutelab.space
    url: https://nitter.cutelab.space
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us-tx.png
  - name: nitter.nl
    url: https://nitter.nl
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/nl.png
  - name: nitter.mint.lgbt
    url: https://nitter.mint.lgbt
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: nitter.bus-hit.me
    url: https://nitter.bus-hit.me
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
    assignees:
      - austinhuang0131
  - name: fuckthesacklers.network
    url: https://fuckthesacklers.network
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/zz.png
  - name: nitter.govt.land
    url: https://nitter.govt.land
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/zz.png
  - name: nitter.esmailelbob.xyz
    url: https://nitter.esmailelbob.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: tw.artemislena.eu
    url: https://tw.artemislena.eu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: de.nttr.stream
    url: https://de.nttr.stream
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.winscloud.net
    url: https://nitter.winscloud.net
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/th.png
  - name: nitter.tiekoetter.com
    url: https://nitter.tiekoetter.com
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.spaceint.fr
    url: https://nitter.spaceint.fr
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/be.png
  - name: twtr.bch.bar
    url: https://twtr.bch.bar
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/zz.png
  - name: nitter.privacy.com.de
    url: https://nitter.privacy.com.de
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.mastodon.pro
    url: https://nitter.mastodon.pro
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ch.png
  - name: nitter.notraxx.ch
    url: https://nitter.notraxx.ch
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.poast.org
    url: https://nitter.poast.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: nitter.lunar.icu
    url: https://nitter.lunar.icu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: nitter.bird.froth.zone
    url: https://nitter.bird.froth.zone
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ca.png
  - name: nitter.dcs0.hu
    url: https://nitter.dcs0.hu
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/hu.png
  - name: twitter.dr460nf1r3.org
    url: https://twitter.dr460nf1r3.org
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: twitter.beparanoid.de
    url: https://twitter.beparanoid.de
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/ch.png
  - name: n.ramle.be
    url: https://n.ramle.be
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/be.png

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: xnaas.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /nitter-instances
  logoUrl: https://raw.githubusercontent.com/zedeus/nitter/master/public/favicon-32x32.png
  name: Nitter Instances
  introTitle: "Nitter Instances Uptime"
  introMessage: This status page monitors [Nitter instances](https://github.com/zedeus/nitter/wiki/Instances) for uptime.
  navbar:
    - title: Status
      href: /nitter-instances
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
